# Generated by Django 5.2.4 on 2025-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_shop_sizes_news_views_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='electrician.jpg', upload_to='img'),
        ),
    ]
