# Generated by Django 5.2.4 on 2025-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=100, unique=True, verbose_name='master')),
                ('img', models.ImageField(default='electrician.jpg', upload_to='img')),
            ],
        ),
    ]
