# Generated by Django 5.2.4 on 2025-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_masters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masters',
            options={'verbose_name': 'Master', 'verbose_name_plural': 'Masters'},
        ),
        migrations.AddField(
            model_name='masters',
            name='masterName',
            field=models.SlugField(default='MasterName', verbose_name='MasterName'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='img',
            field=models.ImageField(default='electrician.jpg', upload_to='img', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='master',
            field=models.CharField(max_length=100, unique=True, verbose_name='Мастер'),
        ),
    ]
