# Generated by Django 5.2.4 on 2025-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_masters_options_masters_mastername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='masterName',
        ),
        migrations.AddField(
            model_name='masters',
            name='slug',
            field=models.SlugField(default='MasterName', verbose_name='slug'),
        ),
    ]
