# Generated by Django 5.2.4 on 2025-09-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_masters_mastername_masters_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masters',
            options={},
        ),
    ]
